backend:
  name: github
  repo: gerbilsinspace/gateway # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "public/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - label: 'Pages'
    name: 'pages'
    file: 'src/data/pages/homepage.json'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}