backend:
  name: github
  repo: gerbilsinspace/gateway # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "public/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - label: 'Menu'
    name: 'menu'
    folder: 'src/data/menu'
    create: true
    fields:
      - label: 'Text'
        name: 'text'
        widget: 'string'
      - label: 'Link'
        name: 'link'
        widget: 'string'
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/data/homepage.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Header Image'
            name: 'headerImage'
            widget: 'image'
          - label: 'Menu Colour'
            name: 'menuColour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
          - label: 'Quotes'
            name: 'quotes'
            widget: 'list'
            fields:
              - label: 'Quote'
                name: 'quote'
                widget: 'string'
              - label: 'Author'
                name: 'author'
                widget: 'string'