backend:
  name: github
  repo: gerbilsinspace/gateway # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "public/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - label: 'Menu'
    name: 'menu'
    folder: 'src/data/menu'
    extension: 'json'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Link', name: 'link', widget: 'string'}
      # - {label: 'Parent', name: 'parent', widget: 'relation', collection: 'menu', searchField: ['title'], valueField: 'title', required: false}
  - label: 'Footer'
    name: 'footer'
    folder: 'src/data/footer'
    extension: 'json'
    create: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Address'
        name: 'address'
        widget: 'object'
        fields: 
          - label: 'Name'
            name: 'name'
            widget: 'string'
          - label: 'Address Line 1'
            name: 'addressLine1'
            widget: 'string'
          - label: 'Address Line 2'
            name: 'addressLine2'
            widget: 'string'
          - label: 'City'
            name: 'city'
            widget: 'string'
          - label: 'Postcode'
            name: 'postcode'
            widget: 'string'
      - label: 'Contact'
        name: 'contact'
        widget: 'object'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Contact number'
            name: 'contactNumber'
            widget: 'string'
          - label: 'Email'
            name: 'email'
            widget: 'string'


  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/data/homepage.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Header Image'
            name: 'headerImage'
            widget: 'image'
          - label: 'Menu Colour'
            name: 'menuColour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
          - label: 'Call To Actions'
            name: 'cta'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'deck'
                widget: 'text'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Colour'
                name: 'colour'
                widget: 'select'
                options:
                  - {label: 'Red', value: 'red'}
                  - {label: 'Orange', value: 'orange'}
                  - {label: 'Purple', value: 'purple'}
                  - {label: 'Green', value: 'green'}
          - label: 'Quotes'
            name: 'quotes'
            widget: 'list'
            fields:
              - label: 'Quote'
                name: 'quote'
                widget: 'string'
              - label: 'Author'
                name: 'author'
                widget: 'string'
          - label: 'Description'
            name: 'deck'
            widget: 'text'
          - label: 'Colour'
            name: 'colour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
          - label: 'Image'
            name: 'image'
            widget: 'image'
