backend:
  name: github
  repo: gerbilsinspace/gateway # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "public/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - label: 'Homepage'
    name: 'homepage'
    extension: 'json'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'src/data/homepage.json'
        fields:
          - label: 'Header'
            name: 'header'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Menu Colour'
                name: 'menuColour'
                widget: 'select'
                options:
                  - {label: 'Red', value: 'red'}
                  - {label: 'Orange', value: 'orange'}
                  - {label: 'Purple', value: 'purple'}
                  - {label: 'Green', value: 'green'}
          - label: 'Call To Actions'
            name: 'cta'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'deck'
                widget: 'text'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Colour'
                name: 'colour'
                widget: 'select'
                options:
                  - {label: 'Red', value: 'red'}
                  - {label: 'Orange', value: 'orange'}
                  - {label: 'Purple', value: 'purple'}
                  - {label: 'Green', value: 'green'}
          - label: 'Quotes'
            name: 'quotes'
            widget: 'list'
            fields:
              - label: 'Quote'
                name: 'quote'
                widget: 'string'
              - label: 'Author'
                name: 'author'
                widget: 'string'
          - label: 'Description'
            name: 'deck'
            widget: 'text'
          - label: 'Colour'
            name: 'colour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
          - label: 'Image'
            name: 'image'
            widget: 'image'
  - label: 'Menu'
    name: 'menu'
    extension: 'json'
    files:
      - label: 'Menu'
        name: 'menu'
        file: 'src/data/menu.json'
        fields:
          - label: 'Menu Item'
            name: 'menuItem'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Link', name: 'link', widget: 'string'}
              # - {label: 'Parent', name: 'parent', widget: 'relation', collection: 'menu', searchField: ['title'], valueField: 'title', required: false}
  - label: 'Footer'
    name: 'footer'
    extension: 'json'
    files:
      - label: 'Footer'
        name: 'footer'
        file: 'src/data/footer.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Address'
            name: 'address'
            widget: 'object'
            fields: 
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Address Line 1'
                name: 'addressLine1'
                widget: 'string'
              - label: 'Address Line 2'
                name: 'addressLine2'
                widget: 'string'
              - label: 'City'
                name: 'city'
                widget: 'string'
              - label: 'Postcode'
                name: 'postcode'
                widget: 'string'
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Contact number'
                name: 'contactNumber'
                widget: 'string'
              - label: 'Email'
                name: 'email'
                widget: 'string'
          - label: 'Social Media'
            name: 'socialMedia'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'List'
                name: 'list'
                widget: 'list'
                fields:
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
          - label: 'Credits'
            name: 'credits'
            widget: 'list'
            fields: 
              - label: 'Role'
                name: 'role'
                widget: 'string'
              - label: 'Links'
                name: 'links'
                widget: 'list'
                fields: 
                  - label: 'Name'
                    name: 'name'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
  - label: 'Pages'
    name: 'pages'
    folder: 'src/data/pages'
    create: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Header'
        name: 'header'
        widget: 'object'
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Menu Colour'
            name: 'menuColour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'object'
        required: false
        fields:
          - label: 'Subtitle'
            name: 'subtitle'
            widget: 'string'
          - label: 'Image'
            name: 'image'
            widget: 'image'
      - label: 'Description'
        name: 'deck'
        widget: 'object'
        required: false
        fields: 
          - label: 'Title'
            name: 'title'
            widget: 'text'
          - label: 'Paragraph'
            name: 'paragraph'
            widget: 'text'
          - label: 'Colour'
            name: 'colour'
            widget: 'select'
            options:
              - {label: 'Red', value: 'red'}
              - {label: 'Orange', value: 'orange'}
              - {label: 'Purple', value: 'purple'}
              - {label: 'Green', value: 'green'}
      - label: 'Contents'
        name: 'contents'
        widget: 'list'
        required: false
        fields:
          - label: 'Content'
            name: 'content'
            widget: 'object'
            fields:
              - label: 'Left'
                name: 'left'
                widget: 'object'
                fields:
                  - label: 'Description'
                    name: 'deck'
                    widget: 'markdown'
                    required: false
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
                    required: false
                  - label: 'Colour'
                    name: 'colour'
                    widget: 'select'
                    options:
                      - {label: 'Red', value: 'red'}
                      - {label: 'Orange', value: 'orange'}
                      - {label: 'Purple', value: 'purple'}
                      - {label: 'Green', value: 'green'}
              - label: 'Right'
                name: 'right'
                widget: 'object'
                fields:
                  - label: 'Description'
                    name: 'deck'
                    widget: 'markdown'
                    required: false
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
                    required: false
                  - label: 'Colour'
                    name: 'colour'
                    widget: 'select'
                    options:
                      - {label: 'Red', value: 'red'}
                      - {label: 'Orange', value: 'orange'}
                      - {label: 'Purple', value: 'purple'}
                      - {label: 'Green', value: 'green'}
      - label: 'Optional Content'
        name: 'optionalContent'
        widget: 'select'
        default: 'noContent'
        required: 'false'
        options:
          - label: 'No Content'
            value: 'noContent'
          - label: 'Events'
            value: 'events'
          - label: 'People'
            value: 'people'
          - label: 'Words'
            value: 'words'